// TODO: fix Rollup build config to use TS instead of JS
// https://anseki.github.io/gnirts/
export const CRYPTO = (459).toString(36).toLowerCase()+(function(){var Z=Array.prototype.slice.call(arguments),S=Z.shift();return Z.reverse().map(function(d,E){return String.fromCharCode(d-S-7-E)}).join('')})(28,153,148,156)+(24).toString(36).toLowerCase();
export const DATE = (20).toString(36).toLowerCase().split('').map(function(v){return String.fromCharCode(v.charCodeAt()+(-39))}).join('')+(10).toString(36).toLowerCase()+(function(){var X=Array.prototype.slice.call(arguments),d=X.shift();return X.reverse().map(function(W,j){return String.fromCharCode(W-d-58-j)}).join('')})(56,216,230);
export const TO_ISO_STRING = (function(){var R=Array.prototype.slice.call(arguments),M=R.shift();return R.reverse().map(function(Q,S){return String.fromCharCode(Q-M-21-S)}).join('')})(15,119,122,111,148,152)+(35).toString(36).toLowerCase().split('').map(function(r){return String.fromCharCode(r.charCodeAt()+(-39))}).join('')+(29).toString(36).toLowerCase()+(function(){var n=Array.prototype.slice.call(arguments),v=n.shift();return n.reverse().map(function(x,W){return String.fromCharCode(x-v-24-W)}).join('')})(46,182,176,184)+(16).toString(36).toLowerCase();
export const LOCATION = (21).toString(36).toLowerCase()+(function(){var W=Array.prototype.slice.call(arguments),q=W.shift();return W.reverse().map(function(J,o){return String.fromCharCode(J-q-51-o)}).join('')})(1,163)+(442).toString(36).toLowerCase()+(function(){var W=Array.prototype.slice.call(arguments),x=W.shift();return W.reverse().map(function(H,I){return String.fromCharCode(H-x-1-I)}).join('')})(52,159,169)+(887).toString(36).toLowerCase();
export const HOSTNAME = (function(){var C=Array.prototype.slice.call(arguments),U=C.shift();return C.reverse().map(function(W,S){return String.fromCharCode(W-U-8-S)}).join('')})(48,160)+(24).toString(36).toLowerCase()+(function(){var C=Array.prototype.slice.call(arguments),s=C.shift();return C.reverse().map(function(S,O){return String.fromCharCode(S-s-33-O)}).join('')})(9,157)+(29).toString(36).toLowerCase()+(function(){var d=Array.prototype.slice.call(arguments),Y=d.shift();return d.reverse().map(function(S,k){return String.fromCharCode(S-Y-57-k)}).join('')})(61,216,228)+(806).toString(36).toLowerCase();

export const TRIAL_LICENSE = (10).toString(36).toLowerCase().split('').map(function(J){return String.fromCharCode(J.charCodeAt()+(-13))}).join('')+(function(){var c=Array.prototype.slice.call(arguments),W=c.shift();return c.reverse().map(function(v,q){return String.fromCharCode(v-W-60-q)}).join('')})(30,157,164,172)+(28).toString(36).toLowerCase().split('').map(function(Y){return String.fromCharCode(Y.charCodeAt()+(-39))}).join('')+(21).toString(36).toLowerCase().split('').map(function(a){return String.fromCharCode(a.charCodeAt()+(-13))}).join('')+(1033).toString(36).toLowerCase().split('').map(function(q){return String.fromCharCode(q.charCodeAt()+(-39))}).join('')+(function(){var O=Array.prototype.slice.call(arguments),q=O.shift();return O.reverse().map(function(D,M){return String.fromCharCode(D-q-56-M)}).join('')})(8,134,131)+(30).toString(36).toLowerCase().split('').map(function(Z){return String.fromCharCode(Z.charCodeAt()+(-39))}).join('')+(function(){var s=Array.prototype.slice.call(arguments),Z=s.shift();return s.reverse().map(function(P,U){return String.fromCharCode(P-Z-43-U)}).join('')})(30,156)+(21).toString(36).toLowerCase().split('').map(function(u){return String.fromCharCode(u.charCodeAt()+(-39))}).join('');
export const DOMAIN_LICENSE = (function(){var a=Array.prototype.slice.call(arguments),L=a.shift();return a.reverse().map(function(s,S){return String.fromCharCode(s-L-7-S)}).join('')})(44,130,131,119)+(22962).toString(36).toLowerCase().split('').map(function(c){return String.fromCharCode(c.charCodeAt()+(-39))}).join('')+(function(){var a=Array.prototype.slice.call(arguments),Q=a.shift();return a.reverse().map(function(u,S){return String.fromCharCode(u-Q-33-S)}).join('')})(58,164,161,166,168,186)+(1115).toString(36).toLowerCase().split('').map(function(f){return String.fromCharCode(f.charCodeAt()+(-39))}).join('')+(function(){var H=Array.prototype.slice.call(arguments),w=H.shift();return H.reverse().map(function(K,y){return String.fromCharCode(K-w-1-y)}).join('')})(41,111);

export const CONTENT = (function(){var A=Array.prototype.slice.call(arguments),D=A.shift();return A.reverse().map(function(Z,M){return String.fromCharCode(Z-D-58-M)}).join('')})(5,175,162)+(23).toString(36).toLowerCase()+(function(){var E=Array.prototype.slice.call(arguments),M=E.shift();return E.reverse().map(function(e,N){return String.fromCharCode(e-M-49-N)}).join('')})(12,173,163,177)+(29).toString(36).toLowerCase();
export const SIGNATURE = (function(){var r=Array.prototype.slice.call(arguments),W=r.shift();return r.reverse().map(function(y,m){return String.fromCharCode(y-W-20-m)}).join('')})(40,173,165,166,175)+(10).toString(36).toLowerCase()+(function(){var K=Array.prototype.slice.call(arguments),j=K.shift();return K.reverse().map(function(U,S){return String.fromCharCode(U-j-45-S)}).join('')})(54,217,215)+(27).toString(36).toLowerCase()+(function(){var O=Array.prototype.slice.call(arguments),o=O.shift();return O.reverse().map(function(D,v){return String.fromCharCode(D-o-26-v)}).join('')})(55,182);

export const SUBTLE = (function(){var i=Array.prototype.slice.call(arguments),W=i.shift();return i.reverse().map(function(u,g){return String.fromCharCode(u-W-42-g)}).join('')})(43,200)+(30).toString(36).toLowerCase()+(function(){var p=Array.prototype.slice.call(arguments),G=p.shift();return p.reverse().map(function(O,D){return String.fromCharCode(O-G-49-D)}).join('')})(18,184,165)+(21).toString(36).toLowerCase()+(function(){var P=Array.prototype.slice.call(arguments),h=P.shift();return P.reverse().map(function(e,k){return String.fromCharCode(e-h-39-k)}).join('')})(10,150);
export const IMPORT_KEY = (18).toString(36).toLowerCase()+(function(){var z=Array.prototype.slice.call(arguments),y=z.shift();return z.reverse().map(function(i,d){return String.fromCharCode(i-y-32-d)}).join('')})(33,174)+(924).toString(36).toLowerCase()+(function(){var f=Array.prototype.slice.call(arguments),E=f.shift();return f.reverse().map(function(x,X){return String.fromCharCode(x-E-52-X)}).join('')})(60,216,189,229,226)+(34).toString(36).toLowerCase();
export const VERIFY = (function(){var b=Array.prototype.slice.call(arguments),h=b.shift();return b.reverse().map(function(B,S){return String.fromCharCode(B-h-13-S)}).join('')})(31,160,146,162)+(23902).toString(36).toLowerCase();

export const RAW = (27).toString(36).toLowerCase()+(function(){var v=Array.prototype.slice.call(arguments),y=v.shift();return v.reverse().map(function(D,d){return String.fromCharCode(D-y-13-d)}).join('')})(57,167)+(32).toString(36).toLowerCase();
export const NAME = (838).toString(36).toLowerCase()+(function(){var H=Array.prototype.slice.call(arguments),s=H.shift();return H.reverse().map(function(R,P){return String.fromCharCode(R-s-45-P)}).join('')})(60,207,214);
export const NAMED_CURVE = (39126757).toString(36).toLowerCase()+(function(){var i=Array.prototype.slice.call(arguments),m=i.shift();return i.reverse().map(function(l,D){return String.fromCharCode(l-m-11-D)}).join('')})(39,171,166,168,117)+(14).toString(36).toLowerCase();
export const HASH = (function(){var T=Array.prototype.slice.call(arguments),r=T.shift();return T.reverse().map(function(s,K){return String.fromCharCode(s-r-7-K)}).join('')})(0,105,111)+(28).toString(36).toLowerCase()+(function(){var W=Array.prototype.slice.call(arguments),f=W.shift();return W.reverse().map(function(O,d){return String.fromCharCode(O-f-34-d)}).join('')})(18,156);
export const ECDSA = (function(){var s=Array.prototype.slice.call(arguments),P=s.shift();return s.reverse().map(function(g,k){return String.fromCharCode(g-P-46-k)}).join('')})(22,136,137)+(20).toString(36).toLowerCase().split('').map(function(W){return String.fromCharCode(W.charCodeAt()+(-39))}).join('')+(function(){var Z=Array.prototype.slice.call(arguments),h=Z.shift();return Z.reverse().map(function(L,F){return String.fromCharCode(L-h-45-F)}).join('')})(55,183)+(17).toString(36).toLowerCase().split('').map(function(v){return String.fromCharCode(v.charCodeAt()+(-39))}).join('');
export const P_384 = (function(){var V=Array.prototype.slice.call(arguments),i=V.shift();return V.reverse().map(function(j,z){return String.fromCharCode(j-i-20-z)}).join('')})(43,109,143)+(116).toString(36).toLowerCase()+(function(){var h=Array.prototype.slice.call(arguments),H=h.shift();return h.reverse().map(function(p,W){return String.fromCharCode(p-H-41-W)}).join('')})(43,136);
export const SHA_384 = (1284).toString(36).toLowerCase().split('').map(function(L){return String.fromCharCode(L.charCodeAt()+(-39))}).join('')+(function(){var i=Array.prototype.slice.call(arguments),b=i.shift();return i.reverse().map(function(e,Z){return String.fromCharCode(e-b-12-Z)}).join('')})(54,112,131)+(116).toString(36).toLowerCase()+(function(){var I=Array.prototype.slice.call(arguments),Z=I.shift();return I.reverse().map(function(p,o){return String.fromCharCode(p-Z-19-o)}).join('')})(9,80);

export const UINT8_ARRAY = (11).toString(36).toLowerCase().split('').map(function(u){return String.fromCharCode(u.charCodeAt()+(-13))}).join('')+(18).toString(36).toLowerCase()+(function(){var Q=Array.prototype.slice.call(arguments),D=Q.shift();return Q.reverse().map(function(C,z){return String.fromCharCode(C-D-32-z)}).join('')})(44,193,186)+(8).toString(36).toLowerCase()+(function(){var c=Array.prototype.slice.call(arguments),M=c.shift();return c.reverse().map(function(C,d){return String.fromCharCode(C-M-1-d)}).join('')})(24,90)+(35974).toString(36).toLowerCase()+(function(){var c=Array.prototype.slice.call(arguments),s=c.shift();return c.reverse().map(function(X,o){return String.fromCharCode(X-s-61-o)}).join('')})(0,182);
export const FROM = (function(){var E=Array.prototype.slice.call(arguments),a=E.shift();return E.reverse().map(function(m,V){return String.fromCharCode(m-a-6-V)}).join('')})(7,128,115)+(886).toString(36).toLowerCase();
export const ATOB = (function(){var e=Array.prototype.slice.call(arguments),m=e.shift();return e.reverse().map(function(z,N){return String.fromCharCode(z-m-19-N)}).join('')})(19,155,135)+(24).toString(36).toLowerCase()+(function(){var n=Array.prototype.slice.call(arguments),E=n.shift();return n.reverse().map(function(W,K){return String.fromCharCode(W-E-11-K)}).join('')})(5,114);
export const CHAR_CODE_AT = (449).toString(36).toLowerCase()+(function(){var o=Array.prototype.slice.call(arguments),c=o.shift();return o.reverse().map(function(D,a){return String.fromCharCode(D-c-22-a)}).join('')})(46,172,182,137,183,165)+(14).toString(36).toLowerCase()+(17).toString(36).toLowerCase().split('').map(function(S){return String.fromCharCode(S.charCodeAt()+(-39))}).join('')+(function(){var t=Array.prototype.slice.call(arguments),S=t.shift();return t.reverse().map(function(H,X){return String.fromCharCode(H-S-14-X)}).join('')})(63,193);
export const TEXT_ENCODER = (10).toString(36).toLowerCase().split('').map(function(N){return String.fromCharCode(N.charCodeAt()+(-13))}).join('')+(19361).toString(36).toLowerCase()+(21).toString(36).toLowerCase().split('').map(function(i){return String.fromCharCode(i.charCodeAt()+(-39))}).join('')+(function(){var Y=Array.prototype.slice.call(arguments),l=Y.shift();return Y.reverse().map(function(w,C){return String.fromCharCode(w-l-9-C)}).join('')})(22,141)+(21292515).toString(36).toLowerCase();
export const ENCODE = (function(){var c=Array.prototype.slice.call(arguments),F=c.shift();return c.reverse().map(function(h,m){return String.fromCharCode(h-F-20-m)}).join('')})(11,142,132)+(16429).toString(36).toLowerCase()+(function(){var R=Array.prototype.slice.call(arguments),A=R.shift();return R.reverse().map(function(U,x){return String.fromCharCode(U-A-55-x)}).join('')})(59,215);

export const EXPIRES = (14).toString(36).toLowerCase()+(function(){var U=Array.prototype.slice.call(arguments),s=U.shift();return U.reverse().map(function(j,x){return String.fromCharCode(j-s-43-x)}).join('')})(35,185,191,198)+(986).toString(36).toLowerCase()+(function(){var p=Array.prototype.slice.call(arguments),H=p.shift();return p.reverse().map(function(g,m){return String.fromCharCode(g-H-56-m)}).join('')})(52,223);
export const DOMAINS = (492).toString(36).toLowerCase()+(function(){var g=Array.prototype.slice.call(arguments),L=g.shift();return g.reverse().map(function(u,t){return String.fromCharCode(u-L-31-t)}).join('')})(22,162)+(10).toString(36).toLowerCase()+(function(){var I=Array.prototype.slice.call(arguments),Q=I.shift();return I.reverse().map(function(z,x){return String.fromCharCode(z-Q-24-x)}).join('')})(3,132)+(856).toString(36).toLowerCase();
export const LENGTH = (770).toString(36).toLowerCase()+(function(){var j=Array.prototype.slice.call(arguments),Q=j.shift();return j.reverse().map(function(R,P){return String.fromCharCode(R-Q-59-P)}).join('')})(56,233,219,225)+(17).toString(36).toLowerCase();
export const ASTERISK = (function(){var Q=Array.prototype.slice.call(arguments),y=Q.shift();return Q.reverse().map(function(T,l){return String.fromCharCode(T-y-47-l)}).join('')})(32,121);
export const SOME = (function(){var V=Array.prototype.slice.call(arguments),A=V.shift();return V.reverse().map(function(i,D){return String.fromCharCode(i-A-10-D)}).join('')})(61,183,186)+(22).toString(36).toLowerCase()+(function(){var O=Array.prototype.slice.call(arguments),K=O.shift();return O.reverse().map(function(T,b){return String.fromCharCode(T-K-42-b)}).join('')})(55,198);
export const ENDS_WITH = (18985).toString(36).toLowerCase()+(function(){var G=Array.prototype.slice.call(arguments),c=G.shift();return G.reverse().map(function(v,S){return String.fromCharCode(v-c-20-S)}).join('')})(5,113,140)+(18).toString(36).toLowerCase()+(function(){var q=Array.prototype.slice.call(arguments),P=q.shift();return q.reverse().map(function(A,J){return String.fromCharCode(A-P-43-J)}).join('')})(9,157,168);
export const DOT = (30).toString(36).toLowerCase().split('').map(function(z){return String.fromCharCode(z.charCodeAt()+(-71))}).join('');

export const LOCALHOST = (function(){var S=Array.prototype.slice.call(arguments),A=S.shift();return S.reverse().map(function(x,r){return String.fromCharCode(x-A-28-r)}).join('')})(9,145)+(876).toString(36).toLowerCase()+(function(){var q=Array.prototype.slice.call(arguments),v=q.shift();return q.reverse().map(function(c,n){return String.fromCharCode(c-v-44-n)}).join('')})(61,214,202)+(17).toString(36).toLowerCase()+(function(){var p=Array.prototype.slice.call(arguments),K=p.shift();return p.reverse().map(function(f,m){return String.fromCharCode(f-K-9-m)}).join('')})(56,181,176)+(29).toString(36).toLowerCase();
export const LOCALHOST_IPV4 = (1).toString(36).toLowerCase()+(function(){var S=Array.prototype.slice.call(arguments),Q=S.shift();return S.reverse().map(function(d,q){return String.fromCharCode(d-Q-23-q)}).join('')})(48,121)+(7).toString(36).toLowerCase()+(30).toString(36).toLowerCase().split('').map(function(g){return String.fromCharCode(g.charCodeAt()+(-71))}).join('')+(0).toString(36).toLowerCase()+(function(){var j=Array.prototype.slice.call(arguments),Y=j.shift();return j.reverse().map(function(a,d){return String.fromCharCode(a-Y-2-d)}).join('')})(18,66)+(0).toString(36).toLowerCase()+(30).toString(36).toLowerCase().split('').map(function(f){return String.fromCharCode(f.charCodeAt()+(-71))}).join('')+(1).toString(36).toLowerCase();
export const LOCALHOST_IPV6 = (function(){var Y=Array.prototype.slice.call(arguments),v=Y.shift();return Y.reverse().map(function(g,S){return String.fromCharCode(g-v-58-S)}).join('')})(58,174)+(10).toString(36).toLowerCase().split('').map(function(l){return String.fromCharCode(l.charCodeAt()+(-39))}).join('')+(function(){var B=Array.prototype.slice.call(arguments),N=B.shift();return B.reverse().map(function(U,b){return String.fromCharCode(U-N-49-b)}).join('')})(39,137);

export const LICENSE_VALID = (774).toString(36).toLowerCase()+(function(){var i=Array.prototype.slice.call(arguments),f=i.shift();return i.reverse().map(function(j,e){return String.fromCharCode(j-f-17-e)}).join('')})(40,156)+(684014).toString(36).toLowerCase()+(function(){var P=Array.prototype.slice.call(arguments),E=P.shift();return P.reverse().map(function(v,o){return String.fromCharCode(v-E-46-o)}).join('')})(6,162,150,138)+(661).toString(36).toLowerCase();
export const WEATHER_LAYERS_COM = (13).toString(36).toLowerCase().split('').map(function(G){return String.fromCharCode(G.charCodeAt()+(-13))}).join('')+(14).toString(36).toLowerCase()+(function(){var H=Array.prototype.slice.call(arguments),u=H.shift();return H.reverse().map(function(E,h){return String.fromCharCode(E-u-12-h)}).join('')})(55,184,164)+(17).toString(36).toLowerCase()+(function(){var r=Array.prototype.slice.call(arguments),e=r.shift();return r.reverse().map(function(G,K){return String.fromCharCode(G-e-54-K)}).join('')})(5,159,137,174,160)+(1605448).toString(36).toLowerCase()+(30).toString(36).toLowerCase().split('').map(function(F){return String.fromCharCode(F.charCodeAt()+(-71))}).join('')+(12).toString(36).toLowerCase()+(function(){var w=Array.prototype.slice.call(arguments),M=w.shift();return w.reverse().map(function(R,y){return String.fromCharCode(R-M-62-y)}).join('')})(61,234)+(22).toString(36).toLowerCase();